name: ayo_kesitu
description: "Aplikasi Mobile Trip kemana saja."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utils
  get: 4.6.6
  http: 1.2.1
  dio: 5.4.3+1
  url_launcher: 6.2.6
  flutter_screenutil: 5.9.1
  flutter_downloader: 1.11.7
  image_picker: ^0.8.5+3  # Tambahkan dari config kedua
  provider: ^6.0.0        # Tambahkan dari config kedua

  # style
  google_fonts: 6.2.1
  flex_color_scheme: 7.3.1
  simple_shadow: 0.3.1
  intl: 0.19.0

  # security
  envied: 0.5.4+1
  path_provider: 2.1.3
  permission_handler: 11.3.1
  flutter_secure_storage: 9.0.0

  # widget
  flutter_staggered_grid_view: 0.7.0
  file_picker: 8.0.3
  percent_indicator: 4.2.3
  cached_network_image: 3.3.1
  flutter_svg: 2.0.10+1
  dropdown_button2: 2.3.9
  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  envied_generator: 0.5.4+1
  build_runner: 2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/videos/
    - assets/img/Ratenggaro-village-in-Sumba-Explore-Sumba-island-villages-in-Indonesia-10.jpg
    - assets/img/bali.png
    - assets/img/lombok.jpg
    - assets/img/91.png
    - assets/img/gili-islands-digital-nomads.png
    - assets/img/Lombok-to-Komodo-Island-4-Days-3-Night-Amazing-Trip.png
